"""
glm_per_viewer.py — per-viewer (within-subject) laughter GLM maps (Block B, R1.1)
================================================================================
Answers R1.1's request to exploit the deep within-subject data: it estimates the
laughter GLM contrast SEPARATELY for each of the four viewers and shows the
activation is present in every individual, not only in the pooled group. With N=4,
this within-subject reliability (across each viewer's episodes/stimuli) is the
appropriate substitute for population-level second-level inference.

INPUT  (data/b_laughter/, both produced by glm_contrast.py — a SINGLE authoritative
        GLM fit, so per-viewer and group results cannot diverge)
  glm_beta_by_subject_episode.npy   (n_ep, N_SUBJECTS, 1032) per-viewer betas
  glm_episodes.csv                  episode / season index (for reference)

METHOD  per viewer:
  - mean laughter beta across that viewer's present episodes (per parcel) → β map
  - one-sample t vs 0 across that viewer's episodes for the a-priori ROIs
    (within-subject reliability across stimuli)
  inter-viewer agreement: pairwise spatial r between the four cortical β maps.

OUTPUTS (data/b_laughter/)
  glm_per_viewer.csv              viewer × ROI: beta, t, p, n_episodes
  glm_per_viewer_consistency.csv  N_SUBJECTS × N_SUBJECTS inter-viewer spatial-r matrix
  glm_per_viewer_stats.txt        headline agreement + ROI table
FIGURE  (results/analysis_plots/b_laughter/)
  (figure moved to figures/scripts/panel_fig2_per_viewer.py, 2026-08-06 —
                                  replaces the carried-over orphan of the same name)
  (tiered by plot_laughter.py)

Usage
  python glm_per_viewer.py           # skip if glm_per_viewer.csv exists
  python glm_per_viewer.py --force
"""

import argparse
import sys
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from scipy import stats

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))
from config import (
    B_DIR, B_FIG_DIR, SUBJECTS, N_SUBJECTS, N_PARCELS,
    ROI_RTPJ_LAUGHTER, ROI_VISUAL_LOC, ROI_AUDITORY,
)

READOUT = {"rTPJ": ROI_RTPJ_LAUGHTER, "visual_cortex": ROI_VISUAL_LOC, "auditory_cortex": ROI_AUDITORY}


def main():
    ap = argparse.ArgumentParser(); ap.add_argument("--force", action="store_true")
    args = ap.parse_args()
    B_DIR.mkdir(parents=True, exist_ok=True); B_FIG_DIR.mkdir(parents=True, exist_ok=True)
    out_csv = B_DIR / "glm_per_viewer.csv"
    if out_csv.exists() and not args.force:
        print((B_DIR / "glm_per_viewer_stats.txt").read_text()); return

    subj_path = B_DIR / "glm_beta_by_subject_episode.npy"
    if not subj_path.exists():
        sys.exit("Missing glm_beta_by_subject_episode.npy — run "
                 "scripts/b_laughter/glm_contrast.py --force first.")
    B = np.load(subj_path)                       # (n_ep, N_SUBJECTS, 1032)
    n_ep = B.shape[0]

    # per-viewer mean cortical β map + a-priori ROI within-subject t-tests
    maps = np.full((N_SUBJECTS, N_PARCELS), np.nan)
    rows = []
    for s in range(N_SUBJECTS):
        present = ~np.isnan(B[:, s, :N_PARCELS]).all(axis=1)   # episodes this viewer has
        maps[s] = np.nanmean(B[present, s, :N_PARCELS], axis=0)
        for name, idx in READOUT.items():
            vals = B[present, s, idx]
            vals = vals[~np.isnan(vals)]
            t, p = stats.ttest_1samp(vals, 0)
            rows.append({"viewer": SUBJECTS[s], "roi": name, "n_episodes": int(present.sum()),
                         "beta": float(np.mean(vals)), "t": float(t), "p": float(p)})
    df = pd.DataFrame(rows); df.to_csv(out_csv, index=False)

    # inter-viewer spatial agreement (cortical β maps)
    R = np.corrcoef(maps)
    pd.DataFrame(R, index=SUBJECTS, columns=SUBJECTS).to_csv(
        B_DIR / "glm_per_viewer_consistency.csv")
    off = R[np.triu_indices(N_SUBJECTS, k=1)]

    lines = ["Per-viewer laughter GLM (within-subject, Block B, R1.1)",
             "=" * 60,
             f"N viewers = {N_SUBJECTS}  |  episodes with GLM = {n_ep}",
             f"Inter-viewer spatial agreement (cortical beta maps): mean pairwise "
             f"r = {off.mean():.3f} +/- {off.std():.3f}  (range {off.min():.3f}-{off.max():.3f})",
             "",
             f"{'viewer':<9}{'ROI':<16}{'beta':>9}{'t':>8}{'p':>11}{'n_ep':>6}"]
    for _, r in df.iterrows():
        lines.append(f"{r.viewer:<9}{r.roi:<16}{r.beta:>9.3f}{r.t:>8.2f}{r.p:>11.2e}{int(r.n_episodes):>6}")
    txt = "\n".join(lines)
    (B_DIR / "glm_per_viewer_stats.txt").write_text(txt + "\n"); print("\n" + txt)

    # NOTE: this script no longer draws a figure. The Figure 2 panel-C montage
    # is generated by figures/scripts/panel_fig2_per_viewer.py (moved 2026-08-06)
    # from the same arrays, so paper figures come from the figures layer.
    print(f"\nOutputs: {B_DIR}")


if __name__ == "__main__":
    main()
