"""
panel_fig2_glm_brain.py — Figure 2, Panel B (whole-brain GLM laughter contrast).

MOVED HERE 2026-08-06. This panel used to be generated by gen_glm_brain() inside
the ANALYSIS script scripts/b_laughter/plot_laughter.py, written to
results/analysis_plots/b_laughter/main/glm_brain.png, and then copied into panels/
by stage_panels.py with its baked-in suptitle cropped off (top 7%). Three problems
with that: a paper figure was being produced by the analysis layer, the crop was a
hack around a title that should not have been drawn, and the panel could not be
regenerated without re-running a Block B analysis stage.

It is now generated directly from the pipeline's own output — data/b_laughter/
glm_contrast.csv (all 1032 regions) — into figures/panels/, like every other panel.
gen_glm_brain() has been removed from plot_laughter.py, so there is exactly one
generator for this image. No suptitle is drawn, so no crop is needed.

WHAT IT SHOWS. Parcel-wise t of the laughter contrast, FDR-thresholded, painted
onto the Schaefer-1000 cortical atlas plus the Melbourne S2 subcortical atlas.
Top row = cortical cuts, bottom row = striatum/subcortical cuts. The per-row title
boxes are kept deliberately (author decision, 2026-08-06).

CAVEAT worth keeping in view: 961 of 1032 regions survive FDR < .05, so this map is
close to unthresholded — with 278 episode-segments the test is enormously powered
and significance is nearly uninformative. What carries the argument is the spatial
PATTERN (rTPJ and LOC positive, auditory negative) and the effect sizes, not the
extent of colour. See config.ROI_* for the a-priori regions.

Colour scale is symmetric, vmax = 99th percentile of |t| over painted regions.
Canvas is black (2026-08-06): nilearn renders each montage on black, so only the
surround and the band between the rows needed setting. Previous white-background
renderings are kept at figures/_old/*_v1_whitebg.png.

  input   : data/b_laughter/glm_contrast.csv   (1032 rows: beta, t, p_fdr)
  output  : figures/panels/fig2_panelB_glm_brain.png
"""
from pathlib import Path
import sys

import numpy as np
import pandas as pd
import nibabel as nib
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parents[1]))
from config import B_DIR, MELBOURNE_ATLAS_DIR, N_PARCELS, FDR_ALPHA

OUT = HERE.parent / "panels" / "fig2_panelB_glm_brain.png"

# ---------------------------------------------------------------- CONFIG ----
ROWS = [([40, 48, 56, 64], "cortical"),
        ([-6, 0, 6, 12],   "striatum / subcortical")]
FIGSIZE   = (15, 6.5)
FACECOLOR = "black"
DPI       = 150
# -----------------------------------------------------------------------------


def contrast_nifti():
    """FDR-thresholded parcel t-map -> volumetric nifti (cortical + subcortical)."""
    from nilearn import datasets, image

    g = pd.read_csv(B_DIR / "glm_contrast.csv")
    t = g["t"].values
    tsig = np.where(g["p_fdr"].values < FDR_ALPHA, t, 0.0)

    tmpl = datasets.load_mni152_template(resolution=2)
    sch = image.resample_to_img(image.load_img(datasets.fetch_atlas_schaefer_2018(
        n_rois=N_PARCELS, yeo_networks=7, resolution_mm=2)["maps"]),
        tmpl, interpolation="nearest")
    sd = sch.get_fdata().astype(int)
    lut = np.zeros(N_PARCELS + 1); lut[1:] = tsig[:N_PARCELS]
    cvol = lut[sd]

    mel = image.resample_to_img(image.load_img(
        str(MELBOURNE_ATLAS_DIR / "Tian_Subcortex_S2_3T_2009cAsym.nii.gz")),
        tmpl, interpolation="nearest")
    md = mel.get_fdata().astype(int)
    lut2 = np.zeros(33); lut2[1:] = tsig[N_PARCELS:N_PARCELS + 32]

    comb = np.where(md > 0, lut2[md], cvol)
    nii = nib.Nifti1Image(comb.astype(np.float32), tmpl.affine)
    vmax = float(np.percentile(np.abs(comb[comb != 0]), 99))
    return nii, tmpl, vmax, int((g["p_fdr"] < FDR_ALPHA).sum()), len(g)


def main():
    from nilearn import plotting

    nii, tmpl, vmax, n_sig, n_tot = contrast_nifti()

    fig = plt.figure(figsize=FIGSIZE, facecolor=FACECOLOR)
    for r, (cuts, lab) in enumerate(ROWS, start=1):
        ax = fig.add_subplot(len(ROWS), 1, r)
        ax.set_facecolor(FACECOLOR)
        plotting.plot_stat_map(
            nii, bg_img=tmpl, threshold=0.01, vmax=vmax, display_mode="z",
            cut_coords=cuts, colorbar=True, axes=ax,
            title=f"GLM laughter contrast (t, FDR<.05) — {lab}",
        )

    OUT.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(OUT, dpi=DPI, bbox_inches="tight", facecolor=FACECOLOR)
    plt.close(fig)
    print(f"generated  {OUT.name}  (vmax {vmax:.1f}, {n_sig}/{n_tot} regions FDR-sig)")


if __name__ == "__main__":
    main()
